version: '3'

services:
  mongodb:
    image: mongo:3.4.19-jessie
    container_name: vimonga-testdb1
    ports:
      - '27020:27017'
    volumes:
      - "./example:/provision"

  mongodb2:
    image: mongo:3.4.19-jessie
    container_name: vimonga-testdb2
    ports:
      - '27021:27017'
    volumes:
      - "./example:/provision"
